[package]
name = "srml-parachain"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
codec = { package = "parity-codec", version = "3.0", default-features = false, features = [ "derive" ] }
rstd = { package = "sr-std", path = "../../core/sr-std", default-features = false }
runtime-primitives = { package = "sr-primitives", path = "../../core/sr-primitives", default-features = false }
rio = { package = "sr-io", path = "../../core/sr-io", default-features = false }
executive = { package = "srml-executive", path = "../executive", default-features = false }

[dev-dependencies]
keyring = { package = "substrate-keyring", path = "../../core/keyring" }
primitives = { package = "substrate-primitives", path = "../../core/primitives" }
executor = { package = "substrate-executor", path = "../../core/executor" }
test-runtime = { package = "substrate-test-runtime", path = "../../core/test-runtime" }

[features]
default = ["std"]
std = [
	"codec/std",
	"rstd/std",
	"rio/std",
	"runtime-primitives/std",
	"executive/std",
]
