[package]
name = "srml-parachain"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
parity-codec = { version = "3.0", default-features = false }
parity-codec-derive = { version = "3.0", default-features = false }
rstd = { package = "sr-std", path = "../../core/sr-std", default-features = false }
runtime-primitives = { package = "sr-primitives", path = "../../core/sr-primitives", default-features = false }
sr-io = { path = "../../core/sr-io", default-features = false }
executive = { package = "srml-executive", path = "../executive", default-features = false }

[features]
default = ["std"]
std = [
	"parity-codec/std",
	"parity-codec-derive/std",
	"rstd/std",
	"sr-io/std",
	"runtime-primitives/std",
	"executive/std",
]
